cheminformatics for MTG: rdock
TGAC/earlham-galaxytools pull request #41
Opened 2016-12-14 21:44 UTC by wjurkowski

2016-12-14 21:55 UTC, bgruening commented on tools/rdock/rdock.xml
> +    <description>Binding Mode Prediction in Proteins/RNA</description>
A <requirement> should be added here, let me know if you need a conda package as well.

2016-12-14 21:55 UTC, bgruening commented on tools/rdock/rdock.xml
> +    	cat $inputmol2 > inputmol2.mol2; cat $inputprm | sed "s|RECEPTOR_FILE.*|RECEPTOR_FILE inputmol2.mol2|g" | sed "s|REF_MOL.*|REF_MOL ligand.sd|g" > new.prm;
multiple commands should be separated by `&&` not `,`
Please quote all type=data values with a single quote.

2016-12-14 21:55 UTC, bgruening commented on tools/rdock/test-data/rdock/done
> +DONE
is this file really needed?

2016-12-14 21:55 UTC, bgruening commented on tools/rdock/rdock.xml
> +		LD_LIBRARY_PATH=$__tool_directory__/tools/rdock/lib $__tool_directory__/tools/rdock/bin/rbdock -r new.prm -p dock.prm -n 100 -i $inputsd -o output_docking_out > /tmp/docking_out.log;
This all can be avaoided with a conda package.

2016-12-15 10:58 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +    	cat $inputmol2 > inputmol2.mol2; cat $inputprm | sed "s|RECEPTOR_FILE.*|RECEPTOR_FILE inputmol2.mol2|g" | sed "s|REF_MOL.*|REF_MOL ligand.sd|g" > new.prm;
`ln -s '$inputmol2' inputmol2.mol2` is faster than `cat $inputmol2 > inputmol2.mol2` and saves disk space (unless you really need a copy).

2016-12-15 19:07 UTC, wjurkowski commented on tools/rdock/rdock.xml
> +    <description>Binding Mode Prediction in Proteins/RNA</description>
We have it already installed and available as a module but it would be good to have conda recipe for others

2016-12-15 19:08 UTC, wjurkowski commented on tools/rdock/rdock.xml
> +    <description>Binding Mode Prediction in Proteins/RNA</description>
@nsoranzo  Package already installed (ml gcc/4.9.1 && ml rDock/2013.1)

2017-01-10 18:16 UTC, nsoranzo requested changes

2017-01-10 18:16 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +        sdsort -n -f'SCORE' output_docking_out.sd > sorted.sd;
Can you replace all the `;` with `&&`?

So if one of the bash commands fails, the following ones are not executed.

2017-01-10 18:16 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +        <param name="inputsd" format="sd" type="data" label="Input ligand SD file" help="(-i)"/>
It seems that the `prm` and `sd` datatypes are not available in Galaxy, we may open a pull request to add them.

@bgruening Do you know if they are available under a different name maybe?

2017-01-10 18:16 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +        rbcavity -r new.prm -was > /tmp/rbcavity.log;
Use a local file instead of `/tmp`, it is not guaranteed to be available in a cluster system.

2017-01-10 18:16 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +	rbdock -r new.prm -p dock.prm -n 100 -i $inputsd -o output_docking_out > /tmp/docking_out.log;
Use a local file instead of `/tmp`, it is not guaranteed to be available in a cluster system.
Also add single quotes around `$inputsd` .

2017-01-10 18:16 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +    	ln -s $inputmol2 inputmol2.mol2 && cat $inputprm | sed "s|RECEPTOR_FILE.*|RECEPTOR_FILE inputmol2.mol2|g" | sed "s|REF_MOL.*|REF_MOL ligand.sd|g" > new.prm;
All Galaxy variables that contain a dataset path (e.g. the ones associated to a `<param type="data">`) or a user-supplied string (`<param type="text">`) must be quoted using single quotes. So this line should be:
```
ln -s '$inputmol2' inputmol2.mol2 && cat '$inputprm' | sed 's|RECEPTOR_FILE.*|RECEPTOR_FILE inputmol2.mol2|g' | sed 's|REF_MOL.*|REF_MOL ligand.sd|g' > new.prm &&
```

2017-01-10 18:16 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +        cp -r $__tool_directory__/tools/rdock/data .;
I don't think this is going to work, `$__tool_directory__` is translated to the directory where the Galaxy tool XML file is located.

2017-01-10 18:16 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +        cp $inputsd data/ligands/ligand.sd;
Single quotes around `$inputsd`

2017-01-10 18:16 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +        </citation>
You can replace this with a much simpler:
```
<citation type="doi">10.1371/journal.pcbi.1003571</citation>
```

2017-01-10 19:26 UTC, bgruening commented on tools/rdock/rdock.xml
> +        <param name="inputsd" format="sd" type="data" label="Input ligand SD file" help="(-i)"/>
I don't know about `prm` sorry. But `sd` is probably `sdf`.

2017-02-07 23:27 UTC, wjurkowski commented on tools/rdock/rdock.xml
> +        <param name="inputsd" format="sd" type="data" label="Input ligand SD file" help="(-i)"/>
yes, SD stands for SD file, often referred to as SDF

2017-02-07 23:28 UTC, wjurkowski commented on tools/rdock/rdock.xml
> +        </citation>
simple, indeed 👍

2017-02-07 23:31 UTC, wjurkowski commented on tools/rdock/rdock.xml
> +        sdsort -n -f'SCORE' output_docking_out.sd > sorted.sd;
done

2017-02-07 23:32 UTC, wjurkowski commented on tools/rdock/rdock.xml
> +	rbdock -r new.prm -p dock.prm -n 100 -i $inputsd -o output_docking_out > /tmp/docking_out.log;
corrected

2017-02-07 23:34 UTC, wjurkowski commented on tools/rdock/rdock.xml
> +        cp -r $__tool_directory__/tools/rdock/data .;
This is because, initially the tool and example files were located together with XML...

2017-02-10 10:56 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +        <param name="inputsd" format="sd" type="data" label="Input ligand SD file" help="(-i)"/>
Can you change `format="sd"` to `format="sdf"`, which is the datatype name used in Galaxy?

2017-02-10 10:56 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +    	ln -s '$inputmol2' inputmol2.mol2 && cat '$inputprm' | sed 's|RECEPTOR_FILE.*|RECEPTOR_FILE inputmol2.mol2|g' | sed 's|REF_MOL.*|REF_MOL ligand.sd|g' > new.prm;
There's still a `;` at the end of this line to be changed to `&&`.

2017-02-10 17:30 UTC, wjurkowski commented on tools/rdock/test-data/rdock/done
> +DONE
not indeed

2017-02-10 17:43 UTC, wjurkowski commented on tools/rdock/rdock.xml
> +    	ln -s '$inputmol2' inputmol2.mol2 && cat '$inputprm' | sed 's|RECEPTOR_FILE.*|RECEPTOR_FILE inputmol2.mol2|g' | sed 's|REF_MOL.*|REF_MOL ligand.sd|g' > new.prm;
corrected

2017-02-10 17:44 UTC, wjurkowski commented on tools/rdock/rdock.xml
> +        <param name="inputsd" format="sd" type="data" label="Input ligand SD file" help="(-i)"/>
I changed sd to sdf. Prm is not really a data format but too specific way to pass parameters.

2017-02-10 17:44 UTC, wjurkowski commented on tools/rdock/rdock.xml
> +        rbcavity -r new.prm -was > /tmp/rbcavity.log;
done

2017-02-10 19:09 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +    <description>Binding Mode Prediction in Proteins/RNA</description>
@bgruening I'm working on a `rdock` Bioconda recipe, but it depends on [cppunit](https://www.freedesktop.org/wiki/Software/cppunit/), which is not on any of Galaxy default channels. Seems like a candidate for conda-forge?

2017-02-10 19:21 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +        </citation>
Would you mind using the short version? :smiley:

2017-02-10 22:40 UTC, wjurkowski commented
Sure, here it is

On 10 February 2017 at 19:21, Nicola Soranzo <notifications@github.com>
wrote:

> *@nsoranzo* commented on this pull request.
> ------------------------------
>
> In tools/rdock/rdock.xml
> <https://github.com/TGAC/earlham-galaxytools/pull/41>:
>
> > +        <citation type="bibtex">
> +            @article{RuizCarmona2014,
> +              doi = {10.1371/journal.pcbi.1003571},
> +              url = {http://dx.doi.org/10.1371/journal.pcbi.1003571},
> +              year  = {2014},
> +              month = {apr},
> +              publisher = {Public Library of Science ({PLoS})},
> +              volume = {10},
> +              number = {4},
> +              pages = {e1003571},
> +              author = {Sergio Ruiz-Carmona and Daniel Alvarez-Garcia and Nicolas Foloppe and A. Beatriz Garmendia-Doval and Szilveszter Juhos and Peter Schmidtke and Xavier Barril and Roderick E. Hubbard and S. David Morley},
> +              editor = {Andreas Prlic},
> +              title = {{rDock}: A Fast,  Versatile and Open Source Program for Docking Ligands to Proteins and Nucleic Acids},
> +              journal = {{PLoS} Comput Biol}
> +            }
> +        </citation>
>
> Would you mind using the short version? 😃
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TGAC/earlham-galaxytools/pull/41>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADVH8DiWxtLzlufgogD3nNSxJlfuQX0bks5rbLirgaJpZM4LNcvw>
> .
>

2017-03-10 23:07 UTC, nsoranzo requested changes

2017-03-10 23:07 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +        mkdir data/ligands &&
rDock is finally in Bioconda, we can properly test on Travis now! This line should probably be:
```
mkdir -p data/ligands &&
```
mkdir is failing because `data` does not exist.

2017-05-05 16:20 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +        rbcavity -r new.prm -was > rbcavity.log &&
Is the content of `rbcavity.log` interesting for the user? Here is completely lost. You may want to have a output log file or just remove the redirect.

2017-05-05 16:20 UTC, nsoranzo commented on tools/rdock/rdock.xml
> +	rbdock -r new.prm -p dock.prm -n 100 -i '$inputsd' -o output_docking_out > docking_out.log &&
Same for docking_out.log

2017-05-11 16:23 UTC, nsoranzo approved these changes

2017-05-11 21:37 UTC, nsoranzo commented
It's finally green!! Tomorrow I'll cleanup the commits and merge.

2017-05-11 22:50 UTC, wjurkowski commented
Thanks a lot!

On 11 May 2017 at 22:37, Nicola Soranzo <notifications@github.com> wrote:

> It's finally green!! Tomorrow I'll cleanup the commits and merge.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TGAC/earlham-galaxytools/pull/41#issuecomment-300924201>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADVH8ENWjfZ_GSz_fUU-S5QecM7z4dhjks5r43-vgaJpZM4LNcvw>
> .
>

2017-05-12 11:41 UTC, merged