Edited wrappers for R scripts
TGAC/earlham-galaxytools pull request #81
Opened 2017-04-10 11:43 UTC by PerlaTroncosoRey

- Renamed two wrappers (as they now call R scripts instead of MultiPEN standalone application):
   - from: MultiPEN-enrichment-GO.xml,   to: Rscript-enrichment-GO.xml
   - from: MultiPEN-enrichment-KEGG.xml,   to: Rscript-enrichment-KEGG.xml) 

- Added one more wrapper: Rscript-STRINGdb-network.xml.

- Added R scripts:
   - enrichmentGO.R
   - enrichmentKEGG.R
   - compileNetworkStringDB.R

2017-04-10 11:53 UTC, bgruening commented on tools/MultiPEN/Rscript-STRINGdb-network.xml
> +<tool id="STRINGdb-network" name="STRINGdb-network" version="0.0.3">
Can we do the IDs all lower-case?
The name could be `STRINGdb network` this can be free text no need to the dash.

Thanks @PerlaTroncosoRey!

2017-04-17 10:39 UTC, PerlaTroncosoRey commented on tools/MultiPEN/Rscript-STRINGdb-network.xml
> +<tool id="STRINGdb-network" name="STRINGdb-network" version="0.0.3">
sure! will modify the IDs accordingly

2017-05-05 14:38 UTC, nsoranzo commented on tools/MultiPEN/MultiPEN-feature-selection.xml
> +        <param name="optionalParameters" type="string" value="000.500100" label="Optional parameters" help="The digits of this string represent a sequence of parameters. The following triples define
Change `string` to `text`.

2017-05-05 14:39 UTC, nsoranzo commented on tools/MultiPEN/MultiPEN-feature-selection.xml
> +run_MultiPEN_slurm.sh FeatureSelection ./ '$ExpressionData' '$Interactions' '$SampleClass' $lambda $optionalParameters
Add single quotes around `$optionalParameters` (because it's a text param).

2017-05-05 14:40 UTC, nsoranzo commented on tools/MultiPEN/MultiPEN-feature-selection.xml
> +mv MultiPEN-Rankings_lambda${lambda}_genes-higher-in-control_${optionalParameters}.txt Rankings-higherInControl.txt
Add single quotes around all the `MultiPEN-....txt' filenames (again because `${optionalParameters}` is a text param)

2017-05-05 15:12 UTC, nsoranzo requested changes

2017-05-05 15:12 UTC, nsoranzo commented on tools/MultiPEN/Rscript-STRINGdb-network.xml
> +<tool id="stringdb network" name="stringdb-network" version="0.0.3">
The tool id should not contain spaces.

2017-05-05 15:12 UTC, nsoranzo commented on tools/MultiPEN/Rscript-STRINGdb-network.xml
> +        This wrapper compiles a PPI network from a list of genes, using the bioconductor R package STRINGdb: Search Tool for the Retrieval of Interacting Proteins database (see http://bioconductor.or
`bioconductor R` -> `Bioconductor`

2017-05-05 15:12 UTC, nsoranzo commented on tools/MultiPEN/Rscript-enrichment-GO.xml
> +<tool id="enrich go" name="enrich go" version="0.0.3">
No spaces in tool id.

2017-05-05 15:12 UTC, nsoranzo commented on tools/MultiPEN/Rscript-enrichment-GO.xml
> +        <requirement type="package" version="3.3.1">r</requirement>
You can remove the `r` requirement, it's already a depedency of the other R/Bioconductor packages.

2017-05-05 15:12 UTC, nsoranzo commented on tools/MultiPEN/Rscript-enrichment-GO.xml
> +        <requirement type="package" version="1.10">r-BBmisc</requirement>
Only version 1.9 is available in Bioconda, need to update the recipe there or decrease the version here.

2017-05-05 15:12 UTC, nsoranzo commented on tools/MultiPEN/Rscript-enrichment-GO.xml
> +        <citation type="doi">https://doi.org/10.1093/nar/gku1179</citation>
Remove `https://doi.org/`

2017-05-05 15:12 UTC, nsoranzo commented on tools/MultiPEN/Rscript-enrichment-KEGG.xml
> +<tool id="enrich kegg" name="enrich kegg" version="0.0.3">
No spaces in tool id.

2017-05-05 15:12 UTC, nsoranzo commented on tools/MultiPEN/Rscript-enrichment-KEGG.xml
> +        <requirement type="package" version="3.3.1">r</requirement>
Remove `r` requirement.

2017-05-05 15:12 UTC, nsoranzo commented on tools/MultiPEN/Rscript-enrichment-KEGG.xml
> +        <requirement type="package" version="1.10">r-BBmisc</requirement>
As above, only version 1.9 is available in Bioconda, need to update the recipe there or decrease the version here.

2017-05-05 15:12 UTC, nsoranzo commented on tools/MultiPEN/Rscript-enrichment-KEGG.xml
> +            </citation>
You can replace this with:
```xml
        <citation type="doi">0.1093/nar/28.1.27</citation>
```

2025-02-17 14:38 UTC, closed without merging